services:
  reservations:
    container_name: reservations
    build:
      context: ./apps/reservations
      dockerfile: Dockerfile
      target: development
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    env_file:
      - ./docker/environments/mongodb.env

  mongodb:
    container_name: mongodb
    image: mongo:7.0.12
    restart: always
    shm_size: 256mb
    ports:
      - 27017:27017
    env_file:
      - ./docker/environments/mongodb.env
    volumes:
      - ./docker/db/mongodb:/data/mongodb
      - ./docker/configs/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
